import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "모두의민턴",
    description: "Generated by create next app",
    icons: {
        icon: "/logo512.png",
    },
    viewport: {
        width: "device-width",
        initialScale: 1.0,
        maximumScale: 1.0,
        userScalable: false,
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Gaegu:wght@300;400;700&display=swap"
                    rel="stylesheet"
                />
            </head>
            <body className="antialiased">{children}</body>
        </html>
    );
}
